version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - go_network
    restart: on-failure  # Automatically restart the app if it crashes due to DB issues
    # Uncomment if using a wait-for-it script
    # entrypoint: ["/wait-for-it.sh", "mysql:3306", "--", "./transactions"]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - go_network

networks:
  go_network:
    driver: bridge

volumes:
  mysql_data:
